[package]
name = "snmp-parser"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

[dependencies]
libc = "0.2.0"
nom = "1.2.4"
log = "*"
env_logger = "*"
der-parser = { git = "https://github.com/rusticata/der-parser.git" }

